import type { CategoryResponse, MenuItemResponse } from '@/types';
import { IMAGES } from './images';

export const DEMO_CATEGORIES: CategoryResponse[] = [
  { id: 'cat-1', nameEn: 'Coffee', nameAr: 'قهوة', displayOrder: 1, isActive: true, menuItemCount: 3 },
  { id: 'cat-2', nameEn: 'Pastries', nameAr: 'المعجنات', displayOrder: 2, isActive: true, menuItemCount: 2 },
  { id: 'cat-3', nameEn: 'Breakfast', nameAr: 'الإفطار', displayOrder: 3, isActive: true, menuItemCount: 2 },
  { id: 'cat-4', nameEn: 'Cold Drinks', nameAr: 'المشروبات الباردة', displayOrder: 4, isActive: true, menuItemCount: 2 },
];

const NOW = new Date().toISOString();

export const DEMO_MENU_ITEMS: MenuItemResponse[] = [
  {
    id: 'item-1',
    categoryId: 'cat-1',
    categoryNameEn: 'Coffee',
    categoryNameAr: 'قهوة',
    nameEn: 'Signature Cappuccino',
    nameAr: 'كابتشينو لوميير',
    descriptionEn: 'Our house-blend espresso with perfectly steamed milk and delicate latte art.',
    descriptionAr: 'إسبريسو مزيجنا الخاص مع الحليب المبخر بعناية وفن اللاتيه الرقيق.',
    price: 6.50,
    imageUrl: IMAGES.coffee1,
    isAvailable: true,
    isFeatured: true,
    displayOrder: 1,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-2',
    categoryId: 'cat-1',
    categoryNameEn: 'Coffee',
    categoryNameAr: 'قهوة',
    nameEn: 'Cold Brew Noir',
    nameAr: 'كولد برو نوار',
    descriptionEn: 'Slow-steeped for 18 hours, served over ice with a whisper of vanilla.',
    descriptionAr: 'منقوع ببطء لـ 18 ساعة، يُقدم على الثلج مع لمسة خفية من الفانيليا.',
    price: 7.00,
    imageUrl: IMAGES.coffee2,
    isAvailable: true,
    isFeatured: true,
    displayOrder: 2,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-3',
    categoryId: 'cat-1',
    categoryNameEn: 'Coffee',
    categoryNameAr: 'قهوة',
    nameEn: 'Rose Espresso',
    nameAr: 'إسبريسو الورد',
    descriptionEn: 'Double espresso with house-made rose syrup, orange zest, and a hint of cardamom.',
    descriptionAr: 'إسبريسو مزدوج مع شراب الورد المنزلي وقشر البرتقال ولمسة من الهيل.',
    price: 7.50,
    imageUrl: IMAGES.coffee1,
    isAvailable: true,
    isFeatured: false,
    displayOrder: 3,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-4',
    categoryId: 'cat-2',
    categoryNameEn: 'Pastries',
    categoryNameAr: 'المعجنات',
    nameEn: 'Almond Croissant',
    nameAr: 'كرواسون اللوز',
    descriptionEn: 'Buttery, flaky croissant filled with rich almond cream and toasted almonds.',
    descriptionAr: 'كرواسون هش وطري محشو بكريمة اللوز الغنية واللوز المحمص.',
    price: 5.50,
    imageUrl: IMAGES.pastry1,
    isAvailable: true,
    isFeatured: true,
    displayOrder: 1,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-5',
    categoryId: 'cat-2',
    categoryNameEn: 'Pastries',
    categoryNameAr: 'المعجنات',
    nameEn: 'Lavender Éclair',
    nameAr: 'إكلير اللافندر',
    descriptionEn: 'Choux pastry with lavender-infused cream and a delicate violet glaze.',
    descriptionAr: 'معجنات شو محشوة بكريمة اللافندر ومزيّنة بتطيير بنفسجي رقيق.',
    price: 6.00,
    imageUrl: IMAGES.pastry2,
    isAvailable: true,
    isFeatured: false,
    displayOrder: 2,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-6',
    categoryId: 'cat-3',
    categoryNameEn: 'Breakfast',
    categoryNameAr: 'الإفطار',
    nameEn: 'Avocado Toast',
    nameAr: 'توست الأفوكادو',
    descriptionEn: 'Sourdough toast with smashed avocado, poached egg, cherry tomatoes, and chili flakes.',
    descriptionAr: 'خبز محمص مع الأفوكادو المهروس والبيض المسلوق وطماطم كرزية ورقائق الفلفل الحار.',
    price: 12.00,
    imageUrl: IMAGES.coffee2,
    isAvailable: true,
    isFeatured: true,
    displayOrder: 1,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-7',
    categoryId: 'cat-3',
    categoryNameEn: 'Breakfast',
    categoryNameAr: 'الإفطار',
    nameEn: 'Fluffy Pancakes',
    nameAr: 'فطائر خفيفة',
    descriptionEn: 'Three golden pancakes with maple syrup, fresh berries, and whipped cream.',
    descriptionAr: 'ثلاث فطائر ذهبية مع شراب القيقب والتوت الطازج والقشدة المخفوقة.',
    price: 11.00,
    imageUrl: IMAGES.pastry1,
    isAvailable: true,
    isFeatured: false,
    displayOrder: 2,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-8',
    categoryId: 'cat-4',
    categoryNameEn: 'Cold Drinks',
    categoryNameAr: 'المشروبات الباردة',
    nameEn: 'Mango Matcha Latte',
    nameAr: 'لاتيه الماتشا والمانجو',
    descriptionEn: 'Premium matcha blended with oat milk, topped with a swirl of mango purée.',
    descriptionAr: 'ماتشا ممتازة ممزوجة مع حليب الشوفان ومزينة بحلزون من هريس المانجو.',
    price: 8.00,
    imageUrl: IMAGES.coffee1,
    isAvailable: true,
    isFeatured: false,
    displayOrder: 1,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'item-9',
    categoryId: 'cat-4',
    categoryNameEn: 'Cold Drinks',
    categoryNameAr: 'المشروبات الباردة',
    nameEn: 'Rose Lemonade',
    nameAr: 'ليمونادة الورد',
    descriptionEn: 'House-made lemonade infused with rose water and fresh mint, served over crushed ice.',
    descriptionAr: 'ليمونادة منزلية منقوعة بماء الورد والنعناع الطازج، تُقدم على الثلج المجروش.',
    price: 6.50,
    imageUrl: IMAGES.drink1,
    isAvailable: true,
    isFeatured: false,
    displayOrder: 2,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const DEMO_FEATURED_ITEMS = DEMO_MENU_ITEMS.filter(item => item.isFeatured);
